### ISSUE TITLE
How to Push a Dist Folder after Grunt Build?

### ISSUE THREAD

**Issue by louisscruz** [progrium/dokku#1093]
I am trying to push my Angular-Fullstack (yo) MEAN application to Digitalocean via Dokku. When I currently try to push, I get this error:

    fs.js:0
       (function (exports, require, module, __filename, __dirname) { // Copyright Joy
       Error: ENOENT, no such file or directory '/app/public/favicon.ico'
           at Error (native)
           at Object.fs.statSync (fs.js:797:18)
           at favicon (/app/node_modules/serve-favicon/index.js:47:15)
           at module.exports (/app/server/config/express.js:32:13)
           at Object.<anonymous> (/app/server/app.js:28:28)
           at Module._compile (module.js:460:26)
           at Object.Module._extensions..js (module.js:478:10)
           at Module.load (module.js:355:32)
           at Function.Module._load (module.js:310:12)
           at Function.Module.runMain (module.js:501:10)

Now I realize that the favicon file is automatically produced via grunt build. Is there a good way for me to locally run grunt build, then push the resulting dist folder to Dokku? Please forgive my ignorance, I'm very new to deploying node applications in general.

**Comment by michaelshobbs** [comment]
I wrote a [plugin](https://github.com/michaelshobbs/dokku-app-predeploy-tasks) to handle these sorts of tasks. However if this is a grunt build, can't you use a `postinstall` script definition in `package.json`?

**Comment by josegonzalez** [comment]
Yeah, I'd say use a `postinstall` script as mentioned by @michaelshobbs.

Closing since I don't think we can do anything here.
