### ISSUE TITLE
Rails app assets precompile failed

### ISSUE THREAD

**Issue by ipatovanton** [progrium/dokku#1103]
```
MacBook-Pro-Anton:trendmedia ipatov$ git push trendmedia.io master
Counting objects: 168, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (161/161), done.
Writing objects: 100% (168/168), 71.59 KiB | 0 bytes/s, done.
Total 168 (delta 28), reused 0 (delta 0)
-----> Cleaning up...
-----> Building trendmedia.io from buildstep...
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.2.1
-----> Installing dependencies using 1.6.3
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Using json 1.8.2
       Using i18n 0.7.0
       Using minitest 5.5.1
       Using thread_safe 0.3.5
       Using rake 10.4.2
       Using erubis 2.7.0
       Using builder 3.2.2
       Using mini_portile 0.6.2
       Using mime-types 2.4.3
       Using rack 1.6.0
       Using unf_ext 0.0.6
       Using arel 6.0.0
       Using aws_cf_signer 0.1.3
       Using netrc 0.10.3
       Using hike 1.2.3
       Using thor 0.19.1
       Using bundler 1.6.3
       Using tilt 1.4.1
       Using multi_json 1.11.0
       Using bson 2.3.0
       Using bcrypt 3.1.10
       Using chronic 0.10.2
       Using coffee-script-source 1.9.1
       Using execjs 2.5.0
       Using connection_pool 2.1.3
       Using dalli 2.7.4
       Using curb 0.8.7
       Using evil_icons 1.7.2
       Using orm_adapter 0.5.0
       Using multipart-post 2.0.0
       Using sax-machine 1.3.1
       Using hashie 3.4.1
       Using jwt 1.4.1
       Using kgio 2.9.3
       Using origin 2.1.1
       Using optionable 0.2.0
       Using stringex 2.5.2
       Using multi_xml 0.5.5
       Using rails_serve_static_assets 0.0.4
       Using rails_stdout_logging 0.0.3
       Using raindrops 0.13.0
       Using sass 3.2.19
       Using rdoc 4.2.0
       Using tzinfo 1.2.2
       Using mail 2.6.3
       Using nokogiri 1.6.6.2
       Using unf 0.1.4
       Using sprockets 2.12.3
       Using warden 1.2.3
       Using whenever 0.9.4
       Using uglifier 2.7.1
       Using omniauth 1.2.2
       Using coffee-script 2.4.1
       Using rack-test 0.6.3
       Using faraday 0.9.1
       Using moped 2.0.4
       Using rails_12factor 0.0.3
       Using sdoc 0.4.1
       Using activesupport 4.2.1
       Using unicorn 4.8.3
       Using domain_name 0.5.23
       Using oauth2 1.0.0
       Using rails-deprecated_sanitizer 1.0.3
       Using loofah 2.0.1
       Using activemodel 4.2.1
       Using globalid 0.3.3
       Using http-cookie 1.0.2
       Using jbuilder 2.2.12
       Using omniauth-oauth2 1.2.0
       Using activejob 4.2.1
       Using rails-dom-testing 1.0.6
       Using activerecord 4.2.1
       Using rails-html-sanitizer 1.0.2
       Using rest-client 1.8.0
       Using feedjira 1.6.0
       Using mongoid 4.0.2
       Using actionview 4.2.1
       Using omniauth-facebook 2.0.1
       Using cloudinary 1.0.84
       Using mongoid-slug 4.0.0
       Using actionpack 4.2.1
       Using actionmailer 4.2.1
       Using railties 4.2.1
       Using sprockets-rails 2.2.4
       Using kaminari 0.16.3
       Using coffee-rails 4.0.1
       Using rails 4.2.1
       Using responders 2.1.0
       Using jquery-rails 4.0.3
       Using sass-rails 4.0.5
       Using turbolinks 2.5.3
       Using attachinary 1.3.0
       Using devise 3.4.1
       Using jquery-turbolinks 2.1.0
       Using social_shares 0.2.3 from git://github.com/ipatovanton/social_shares.git (at master)
       Your bundle is complete!
       Gems in the groups development and test were not installed.
       It was installed into ./vendor/bundle
       Bundle completed (1.14s)
       Cleaning up the bundler cache.
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       NoMethodError: undefined method `match' for nil:NilClass
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/sessions/mongo_uri.rb:49:in `initialize'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:106:in `new'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:106:in `parse'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:62:in `create_session'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/sessions/factory.rb:43:in `default'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/sessions.rb:37:in `default'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid.rb:65:in `default_session'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/mongoid-4.0.2/lib/mongoid/railtie.rb:104:in `block in <class:Railtie>'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:36:in `call'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:44:in `each'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
       /tmp/build/config/environment.rb:5:in `<top (required)>'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:328:in `require_environment!'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
       !
       !     Precompiling assets failed.
       !
To dokku@trendmedia.io:trendmedia.io
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@trendmedia.io:trendmedia.io'
```

**Comment by josegonzalez** [comment]
From the stacktrace, looks like you may be missing the mongodb connection info, since nil is being passed to [here](https://github.com/mongoid/mongoid/blob/master/lib/mongoid/sessions/mongo_uri.rb#L48). Might want to check that out in your app.
