### ISSUE TITLE
Why is ruby buildback getting node.js and failing?

### ISSUE THREAD

**Issue by joshco** [progrium/dokku#1214]
This really sucks that my ability to deploy my app is dependent on the nodejs.org server's uptime

````
       Bundle completed (12.68s)
       Cleaning up the bundler cache.
/tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/shell_helpers.rb:49:in `       !
       !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 5 --max-time 30 http://nodejs.org/dist/v0.10.30/node-v0.10.30-linux-x64.tar.gz -s -o - | tar zxf - node-v0.10.30-linux-x64/bin/node' failed unexpectedly:
       !
       !     gzip: stdin: unexpected end of file
       !     tar: Child returned status 1
       !     tar: Error is not recoverable: exiting now
Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 5 --max-time 30 http://nodejs.org/dist/v0.10.30/node-v0.10.30-linux-x64.tar.gz -s -o - | tar zxf - node-v0.10.30-linux-x64/bin/node' failed unexpectedly: (LanguagePack::Fetcher::FetchError)

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/fetcher.rb:24:in `fetch_untar'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/helpers/node_installer.rb:39:in `install'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:404:in `block in install_binary'
       !
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:402:in `chdir'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:402:in `install_binary'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:391:in `block (2 levels) in install_binaries'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:391:in `each'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:391:in `block in install_binaries'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
        from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:47:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:43:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:390:in `install_binaries'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:97:in `block (2 levels) in compile'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:672:in `call'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:672:in `allow_git'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:92:in `block in compile'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
        from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:47:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:43:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:83:in `compile'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/rails2.rb:49:in `block in compile'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
        from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:47:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:43:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/rails2.rb:47:in `compile'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/rails3.rb:38:in `block in compile'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
        from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:47:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:43:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/rails3.rb:37:in `compile'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/rails4.rb:41:in `block in compile'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
        from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:47:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:43:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/rails4.rb:40:in `compile'
        from /tmp/buildpacks/heroku-buildpack-ruby/bin/compile:16:in `block (2 levels) in <main>'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:124:in `log'
        from /tmp/buildpacks/heroku-buildpack-ruby/bin/compile:15:in `block in <main>'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:35:in `call'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:35:in `block in trace'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
        from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
        from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:35:in `trace'
        from /tmp/buildpacks/heroku-buildpack-ruby/bin/compile:11:in `<main>'
root@dokku-prod:/home/dokku/tmx#
````

**Comment by joshco** [comment]
ugh. same as #909 
Is our ruby buildback out of date that is is using node.js instead of S3 to get the data.

**Comment by josegonzalez** [comment]
Try setting your BUILDPACK_URL env var.

**Comment by joshco** [comment]
I tried that without success.  as from #909.  Thankfully, the node.js server came back online.

> dokku config:set appname BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-ruby.git

Pushing with that set gave me the following pain:
````
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.0.0
remote: /tmp/buildpacks/custom/lib/language_pack/base.rb:160:in `initialize'
   !
remote:        !     Permission denied - /tmp/buildpacks/custom/export
remote:        !
remote: : Permission denied - /tmp/buildpacks/custom/export (Errno::EACCES)
remote:         from /tmp/buildpacks/custom/lib/language_pack/base.rb:160:in `open'
remote:         from /tmp/buildpacks/custom/lib/language_pack/base.rb:160:in `add_to_export'
remote:         from /tmp/buildpacks/custom/lib/language_pack/base.rb:170:in `set_export_override'
remote:         from /tmp/buildpacks/custom/lib/language_pack/ruby.rb:271:in `block in setup_export'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:17:in `block in instrument'
remote:         from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:16:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/base.rb:48:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/base.rb:44:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/ruby.rb:269:in `setup_export'
remote:         from /tmp/buildpacks/custom/lib/language_pack/ruby.rb:88:in `block in compile'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:17:in `block in instrument'
remote:         from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:16:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/base.rb:48:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/base.rb:44:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/ruby.rb:80:in `compile'
remote:         from /tmp/buildpacks/custom/lib/language_pack/rails2.rb:49:in `block in compile'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:17:in `block in instrument'
remote:         from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:16:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/base.rb:48:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/base.rb:44:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/rails2.rb:47:in `compile'
remote:         from /tmp/buildpacks/custom/lib/language_pack/rails3.rb:38:in `block in compile'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:17:in `block in instrument'
remote:         from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:16:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/base.rb:48:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/base.rb:44:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/rails3.rb:37:in `compile'
remote:         from /tmp/buildpacks/custom/lib/language_pack/rails4.rb:41:in `block in compile'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:17:in `block in instrument'
remote:         from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:16:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/base.rb:48:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/base.rb:44:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/rails4.rb:40:in `compile'
remote:         from /tmp/buildpacks/custom/bin/compile:16:in `block (2 levels)
in <main>'
remote:         from /tmp/buildpacks/custom/lib/language_pack/base.rb:125:in `log'
remote:         from /tmp/buildpacks/custom/bin/compile:15:in `block in <main>'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:35:in `call'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:35:in `block in trace'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:17:in `block in instrument'
remote:         from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:16:in `instrument'
remote:         from /tmp/buildpacks/custom/lib/language_pack/instrument.rb:35:in `trace'
remote:         from /tmp/buildpacks/custom/bin/compile:11:in `<main>'
To dokku@dokku.splitatom.com:tmxdev
 ! [remote rejected] async -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@dokku.splitatom.com:tmxdev'
````

**Comment by michaelshobbs** [comment]
@joshco almost certainly out of date unless you build buildstep from master

**Comment by michaelshobbs** [comment]
related: https://github.com/progrium/buildstep/issues/145

**Comment by michaelshobbs** [comment]
related: 
https://github.com/progrium/buildstep/issues/145
https://github.com/gliderlabs/herokuish/issues/19
https://github.com/progrium/dokku/issues/1091

**Comment by joshco** [comment]
I did it from the repo: https://github.com/progrium/buildstep.git

From the dokku docs I did:
````
cd /tmp
git clone https://github.com/progrium/buildstep.git
cd buildstep
git pull origin master
sudo make build
````

Are there any other steps I need to do?

**Comment by michaelshobbs** [comment]
Hrm. I was just going through debugging this myself. buildstep master is hardcoded to download v0.3.0 of gliderlabs/herokuish which still has the bug. 

https://github.com/progrium/buildstep/blob/85829884c77aaf62f0fe123753b28aa8fe285312/Dockerfile#L3-L4

@progrium please cut a release?

**Comment by wlaurance** [comment]
Is there any update on this?

Thanks! :)

**Comment by michaelshobbs** [comment]
@progrium ping

**Comment by Yachtsman** [comment]
@progrium Any updates here?

**Comment by progrium** [comment]
On it...

**Comment by progrium** [comment]
Trying to do it before vacation...

**Comment by pearlymaccha** [comment]
I got the same problem => "Permission denied - /tmp/buildpacks/custom/export"
How to solve this problem? :(

**Comment by michaelshobbs** [comment]
@josegonzalez @progrium 
 did we ever get a new buildstep release?

**Comment by josegonzalez** [comment]
I don't have access to make buildstep releases. @progrium ping-pong :)

**Comment by progrium** [comment]
Added.

On Mon, Jul 13, 2015 at 9:29 AM, Jose Diaz-Gonzalez <
notifications@github.com> wrote:

> I don't have access to make buildstep releases. @progrium
> <https://github.com/progrium> ping-pong :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/issues/1214#issuecomment-120949174>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by josegonzalez** [comment]
Thanks!

**Comment by michaelshobbs** [comment]
We have a new buildstep/herokuish release. Please update your installs. :smile: Closing.
