### ISSUE TITLE
Herokuish switch broke several of my apps

### ISSUE THREAD

**Issue by darkpixel** [progrium/dokku#1486]
```
       Traceback (most recent call last):
         File "/app/.heroku/python/bin/sentry", line 9, in <module>
           load_entry_point('sentry==7.7.0', 'console_scripts', 'sentry')()
         File "/app/.heroku/python/lib/python2.7/site-packages/sentry/utils/runner.py", line 448, in main
           initializer=initialize_app,
         File "/app/.heroku/python/lib/python2.7/site-packages/logan/runner.py", line 191, in run_app
           configure_app(config_path=config_path, **kwargs)
         File "/app/.heroku/python/lib/python2.7/site-packages/logan/runner.py", line 127, in configure_app
           allow_extras=allow_extras, callback=settings_callback)
         File "/app/.heroku/python/lib/python2.7/site-packages/logan/importer.py", line 37, in install
           sys.meta_path.append(LoganImporter(name, config_path, default_settings, **kwargs))
         File "/app/.heroku/python/lib/python2.7/site-packages/logan/importer.py", line 52, in __init__
           self.validate()
         File "/app/.heroku/python/lib/python2.7/site-packages/logan/importer.py", line 66, in validate
           raise ConfigurationError(unicode(e), exc_info[2])
       logan.importer.ConfigurationError: (u"[Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/app']", <traceback object at 0x7fe48e0f9320>)
```

**Comment by josegonzalez** [comment]
Without a bit more information, we're not able to help debug your issue. Can you provide more the information we request in our [CONTRIBUTING.md](https://github.com/progrium/dokku/blob/master/CONTRIBUTING.md#reporting-other-issues)?

**Comment by michaelshobbs** [comment]
Unfortunately, I don't think we have enough to go on here. I can confirm that `/tmp` exists is and is world-writeable in the herokuish image

```
# dokku/node-js-app is a built out dokku app image based on gliderlabs/herokuish:latest
root@dokku:~# docker run -ti dokku/node-js-app bash
root@1fac915d934a:/# ls -lad /tmp /var/tmp /usr/tmp /app
ls: cannot access /usr/tmp: No such file or directory
drwxr-xr-x 12 u19030 u19030 4096 Sep 22 15:53 /app
drwxrwxrwt 10 root   root   4096 Sep 22 00:33 /tmp
drwxrwxrwt  2 root   root   4096 Apr 10  2014 /var/tmp
root@1fac915d934a:/# su - u19030
u19030@1fac915d934a:~$ touch /tmp/testfile && echo $?
0
```

**Comment by michaelshobbs** [comment]
A cursory googling points to permissions or disk space issues....

**Comment by darkpixel** [comment]
I spent some time digging around the image and couldn't figure out why it was reporting problems.  I ended up re-running ```make install``` for dokku and doing a ```git push``` to re-build all my images.  After the second time they came up without issues.
