### ISSUE TITLE
Postgresql problem after Dokku's update

### ISSUE THREAD

**Issue by maiconsanson** [progrium/dokku#1541]
After a Dokku's update from "0.3.20" to "0.4.1" my postgresql plugin was automatically disabled.

When I try to enable it again with `sudo dokku plugin:enable postgresql` I got `ln: failed to create symbolic link '/var/lib/dokku/plugins/enabled/postgresql': Permission denied`.

obs.: I'm using a user with root privileges.

What could be?

By the way, I'm using https://github.com/Kloadut/dokku-pg-plugin

**Comment by josegonzalez** [comment]
You may need to run that as sudo.

**Comment by maiconsanson** [comment]
@josegonzalez as I sad "I'm using a user with root previleges".
I've updated my issue with the correct SUDO prefix.

**Comment by josegonzalez** [comment]
Interesting that it happens when you also run with the sudo prefix.

Can you gist the output of the following:

```shell
ls -lah /var/lib/dokku/plugins/enabled
```

**Comment by maiconsanson** [comment]
With `ls -lah /var/lib/dokku/plugins/enabled` I have:
```
total 8.0K
drwxr-xr-x 2 root root 4.0K Oct  9 12:49 .
drwxr-xr-x 4 root root 4.0K Oct  9 12:48 ..
lrwxrwxrwx 1 root root   50 Oct  9 12:49 00_dokku-standard -> /var/lib/dokku/plugins/available/00_dokku-standard
lrwxrwxrwx 1 root root   42 Oct  9 12:48 20_events -> /var/lib/dokku/plugins/available/20_events
lrwxrwxrwx 1 root root   37 Oct  9 12:48 apps -> /var/lib/dokku/plugins/available/apps
lrwxrwxrwx 1 root root   39 Oct  9 12:48 backup -> /var/lib/dokku/plugins/available/backup
lrwxrwxrwx 1 root root   42 Oct  9 12:48 build-env -> /var/lib/dokku/plugins/available/build-env
lrwxrwxrwx 1 root root   38 Oct  9 12:48 certs -> /var/lib/dokku/plugins/available/certs
lrwxrwxrwx 1 root root   39 Oct  9 12:49 checks -> /var/lib/dokku/plugins/available/checks
lrwxrwxrwx 1 root root   39 Oct  9 12:49 common -> /var/lib/dokku/plugins/available/common
lrwxrwxrwx 1 root root   39 Oct  9 12:48 config -> /var/lib/dokku/plugins/available/config
lrwxrwxrwx 1 root root   47 Oct  9 12:48 docker-options -> /var/lib/dokku/plugins/available/docker-options
lrwxrwxrwx 1 root root   40 Oct  9 12:49 domains -> /var/lib/dokku/plugins/available/domains
lrwxrwxrwx 1 root root   38 Oct  9 12:48 enter -> /var/lib/dokku/plugins/available/enter
lrwxrwxrwx 1 root root   36 Oct  9 12:48 git -> /var/lib/dokku/plugins/available/git
lrwxrwxrwx 1 root root   37 Oct  9 12:48 logs -> /var/lib/dokku/plugins/available/logs
lrwxrwxrwx 1 root root   45 Oct  9 12:49 nginx-vhosts -> /var/lib/dokku/plugins/available/nginx-vhosts
lrwxrwxrwx 1 root root   39 Oct  9 12:48 plugin -> /var/lib/dokku/plugins/available/plugin
lrwxrwxrwx 1 root root   35 Oct  9 12:49 ps -> /var/lib/dokku/plugins/available/ps
lrwxrwxrwx 1 root root   38 Oct  9 12:48 shell -> /var/lib/dokku/plugins/available/shell
lrwxrwxrwx 1 root root   37 Oct  9 12:48 tags -> /var/lib/dokku/plugins/available/tags
lrwxrwxrwx 1 root root   36 Oct  9 12:48 tar -> /var/lib/dokku/plugins/available/tar
```
With `dokku plugin` I have:

```
00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
cat: /var/lib/dokku/plugins/available/http-auth/plugin.toml: No such file or directory
panic: interface conversion: interface is nil, not map[string]interface {}

goroutine 1 [running]:
runtime.panic(0x5ffd60, 0xc2100530c0)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.TomlGet(0xc21000a030, 0x2, 0x2)
	/tmp/tmp/plugn/plugn.go:30 +0x1d1
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc210010320, 0xc21000a000, 0x5, 0x5, 0x0)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:182 +0x2ac
github.com/progrium/go-basher.Application(0xc21001fdb0, 0x7f4137584f00, 0x4, 0x4, 0x6aeb20, ...)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:64 +0x4d2
main.main()
	/tmp/tmp/plugn/plugn.go:98 +0x431

goroutine 3 [runnable]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31
cat: /var/lib/dokku/plugins/available/http-auth/plugin.toml: No such file or directory
panic: interface conversion: interface is nil, not map[string]interface {}

goroutine 1 [running]:
runtime.panic(0x5ffd60, 0xc2100540c0)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.TomlGet(0xc21000a030, 0x2, 0x2)
	/tmp/tmp/plugn/plugn.go:30 +0x1d1
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc210010320, 0xc21000a000, 0x5, 0x5, 0x0)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:182 +0x2ac
github.com/progrium/go-basher.Application(0xc21001fdb0, 0x7f93b16b9f00, 0x4, 0x4, 0x6aeb20, ...)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:64 +0x4d2
main.main()
	/tmp/tmp/plugn/plugn.go:98 +0x431

goroutine 3 [runnable]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31
  http-auth                  disabled
cat: /var/lib/dokku/plugins/available/link/plugin.toml: No such file or directory
panic: interface conversion: interface is nil, not map[string]interface {}

goroutine 1 [running]:
runtime.panic(0x5ffd60, 0xc2100530c0)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.TomlGet(0xc21000a030, 0x2, 0x2)
	/tmp/tmp/plugn/plugn.go:30 +0x1d1
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc210010320, 0xc21000a000, 0x5, 0x5, 0x0)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:182 +0x2ac
github.com/progrium/go-basher.Application(0xc21001fdb0, 0x7f8eef864f00, 0x4, 0x4, 0x6aeb20, ...)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:64 +0x4d2
main.main()
	/tmp/tmp/plugn/plugn.go:98 +0x431

goroutine 3 [runnable]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31
cat: /var/lib/dokku/plugins/available/link/plugin.toml: No such file or directory
panic: interface conversion: interface is nil, not map[string]interface {}

goroutine 1 [running]:
runtime.panic(0x5ffd60, 0xc2100530c0)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.TomlGet(0xc21000a030, 0x2, 0x2)
	/tmp/tmp/plugn/plugn.go:30 +0x1d1
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc210010320, 0xc21000a000, 0x5, 0x5, 0x0)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:182 +0x2ac
github.com/progrium/go-basher.Application(0xc21001fdb0, 0x7f5381e94f00, 0x4, 0x4, 0x6aeb20, ...)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:64 +0x4d2
main.main()
	/tmp/tmp/plugn/plugn.go:98 +0x431

goroutine 3 [runnable]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31
  link                       disabled
  logs                 0.4.0 enabled    dokku core logs plugin
cat: /var/lib/dokku/plugins/available/memcached/plugin.toml: No such file or directory
panic: interface conversion: interface is nil, not map[string]interface {}

goroutine 1 [running]:
runtime.panic(0x5ffd60, 0xc2100530c0)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.TomlGet(0xc21000a030, 0x2, 0x2)
	/tmp/tmp/plugn/plugn.go:30 +0x1d1
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc210010320, 0xc21000a000, 0x5, 0x5, 0x0)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:182 +0x2ac
github.com/progrium/go-basher.Application(0xc21001fdb0, 0x7f81e68d8f00, 0x4, 0x4, 0x6aeb20, ...)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:64 +0x4d2
main.main()
	/tmp/tmp/plugn/plugn.go:98 +0x431

goroutine 3 [runnable]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31
cat: /var/lib/dokku/plugins/available/memcached/plugin.toml: No such file or directory
panic: interface conversion: interface is nil, not map[string]interface {}

goroutine 1 [running]:
runtime.panic(0x5ffd60, 0xc2100530c0)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.TomlGet(0xc21000a030, 0x2, 0x2)
	/tmp/tmp/plugn/plugn.go:30 +0x1d1
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc210010320, 0xc21000a000, 0x5, 0x5, 0x0)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:182 +0x2ac
github.com/progrium/go-basher.Application(0xc21001fdb0, 0x7f2988e2bf00, 0x4, 0x4, 0x6aeb20, ...)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:64 +0x4d2
main.main()
	/tmp/tmp/plugn/plugn.go:98 +0x431

goroutine 3 [runnable]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31
  memcached                  disabled
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
cat: /var/lib/dokku/plugins/available/postgresql/plugin.toml: No such file or directory
panic: interface conversion: interface is nil, not map[string]interface {}

goroutine 1 [running]:
runtime.panic(0x5ffd60, 0xc2100530c0)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.TomlGet(0xc21000a030, 0x2, 0x2)
	/tmp/tmp/plugn/plugn.go:30 +0x1d1
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc210010320, 0xc21000a000, 0x5, 0x5, 0x0)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:182 +0x2ac
github.com/progrium/go-basher.Application(0xc21001fdb0, 0x7fc0fce10f00, 0x4, 0x4, 0x6aeb20, ...)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:64 +0x4d2
main.main()
	/tmp/tmp/plugn/plugn.go:98 +0x431

goroutine 3 [runnable]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31
cat: /var/lib/dokku/plugins/available/postgresql/plugin.toml: No such file or directory
panic: interface conversion: interface is nil, not map[string]interface {}

goroutine 1 [running]:
runtime.panic(0x5ffd60, 0xc2100530c0)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.TomlGet(0xc21000a030, 0x2, 0x2)
	/tmp/tmp/plugn/plugn.go:30 +0x1d1
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc210010320, 0xc21000a000, 0x5, 0x5, 0x0)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:182 +0x2ac
github.com/progrium/go-basher.Application(0xc21001fdb0, 0x7fbc1cd77f00, 0x4, 0x4, 0x6aeb20, ...)
	/home/vagrant/gocode/src/github.com/progrium/go-basher/basher.go:64 +0x4d2
main.main()
	/tmp/tmp/plugn/plugn.go:98 +0x431

goroutine 3 [runnable]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31
  postgresql                 disabled
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin
```

**Comment by josegonzalez** [comment]
Change your user to root and then try?

**Comment by maiconsanson** [comment]
I've changed to root user with `sudo su` and no news.

My postgresql plugin was automatically disabled (the only one) on Dokku's update.
Is this behaviour expected?

**Comment by josegonzalez** [comment]
Ah, looks like the Kloadut plugin isn't upgraded for usage with 0.4.x. [My fork](https://github.com/josegonzalez/dokku-pg-plugin) of that plugin should work for you. I've already made a PR upstream. We disable incompatible plugins by default.

We currently recommend the official plugins, and have a [postgres](https://github.com/dokku/dokku-postgres) plugin available for your usage. Once you have your data out of the old databases, you can just import it into a new container backed by the official plugin (docs in the readme). Sorry that it's not a bit more seamless/the upgrade process is annoying.

**Comment by maiconsanson** [comment]
Oh yeah, now make sense to me!
Thank you so much for the help. I will change the plugin. No problem about the upgrade process its a very small price for an amazing project.

**Comment by josegonzalez** [comment]
If you can +1 my pull request on Kloadut's project, that would be wonderful.

**Comment by ahmadajmi** [comment]
I have the same issue, and I'm trying to move to `dokku-postgres` from `dokku-pg-plugin`, current app name and DB is: *oktob*

#### Update Dokku

```
cd ~/dokku
git pull --tags origin master
sudo DOKKU_BRANCH=master make install
```

`dokku-pg-plugin` is disabled after Dokku update

$ docker ps

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
d690f2d5fa37        postgresql/oktob    "/usr/bin/start_pgsql"   15 minutes ago      Up 15 minutes       0.0.0.0:49153->5432/tcp   determined_curie
```

$ docker logs oktob

```
2015-11-02T11:42:39.981996584Z oktob[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `initialize': could not connect to server: Connection refused (PG::ConnectionBad)
```

#### Install dokku-postgres

``` dokku plugin:install https://github.com/dokku/dokku-postgres.git postgres ```

#### Create DB

$ dokku postgres:create oktob_db

```
-----> Starting container
       Waiting for container to be ready
       Creating container database
=====> Postgres container created: oktob_db
       DSN: postgres://postgres:65b1b3931826f73980ca85508bc60970@dokku-postgres-oktob-db:5432/oktob_db
```

$ docker ps

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
3e2f40ec3caf        postgres:9.4.4      "/docker-entrypoint.s"   35 seconds ago      Up 34 seconds       5432/tcp                  dokku.postgres.oktob_db
d690f2d5fa37        postgresql/oktob    "/usr/bin/start_pgsql"   22 minutes ago      Up 22 minutes       0.0.0.0:49153->5432/tcp   determined_curie
```

$ dokku postgres:info oktob_db

```
DSN: postgres://postgres:65b1b3931826f73980ca85508bc60970@dokku-postgres-oktob-db:5432/oktob_db
```

$ dokku postgres:link oktob_db oktob

```
-----> Setting config vars
       DOKKU_POSTGRES_BLACK_URL: postgres://postgres:65b1b3931826f73980ca85508bc60970@dokku-postgres-oktob-db:5432/oktob_db
-----> Restarting app oktob
-----> Releasing oktob (dokku/oktob:latest)...
-----> Deploying oktob (dokku/oktob:latest)...
-----> DOKKU_SCALE file found
=====> web=1
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://progrium.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
=====> oktob container output:
=====> end oktob container output
-----> Running post-deploy
-----> Configuring oktob.oktob.io...
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
-----> Shutting down old containers in 60 seconds
=====> 292504c8ee7952606906c4a0ba58eeab21185524f4ade8cef747f8d31c251e4d
=====> Application deployed:
       http://oktob.oktob.io
```

$ docker ps

```
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                     NAMES
ab68ac2e6c7d        dokku/oktob:latest   "/start web"             23 seconds ago      Up 23 seconds                                 oktob.web.1
3e2f40ec3caf        postgres:9.4.4       "/docker-entrypoint.s"   3 minutes ago       Up 3 minutes        5432/tcp                  dokku.postgres.oktob_db
d690f2d5fa37        postgresql/oktob     "/usr/bin/start_pgsql"   25 minutes ago      Up 25 minutes       0.0.0.0:49153->5432/tcp   determined_curie
```

another `ps` after a while

$ docker ps

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
3e2f40ec3caf        postgres:9.4.4      "/docker-entrypoint.s"   4 minutes ago       Up 4 minutes        5432/tcp                  dokku.postgres.oktob_db
d690f2d5fa37        postgresql/oktob    "/usr/bin/start_pgsql"   25 minutes ago      Up 25 minutes       0.0.0.0:49153->5432/tcp   determined_curie
```

but still get `Connection refused (PG::ConnectionBad)`, How I can move to dokku-postgres, a right process for doing this?

Thanks
