### ISSUE TITLE
`rails c` raises in dokku run

### ISSUE THREAD

**Issue by arthurnn** [progrium/dokku#678]
Getting the following error (using latest dokku master, and latest buildstep)
```
dokku run my_rails_app /bin/bash
RAILS_ENV=production bundle exec rails c
/app/vendor/ruby-2.1.2/lib/ruby/2.1.0/irb/completion.rb:9:in `require': libreadline.so.5: cannot open shared object file: No such file or directory - /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/x86_64-linux/readline.so (LoadError)
	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/irb/completion.rb:9:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb:3:in `require'
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb:3:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:128:in `require'
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:128:in `require_command!'
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:59:in `console'
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

To solve the problem I need to open the file `/app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb`, and remove line 3: `require 'irb/completion'`

I guess the problem is that `libreadline.so` is not correct installed, any clue why is that? any guidance in where should I try to fix this problem? I am glad to send a PR,.

**Comment by josegonzalez** [comment]
We updated the buildstep image in use, and also added the `build-env` plugin to allow devs to customize their env vars during a container build. Closing, but feel free to comment if the issue persists on the latest release.
